# Generated by Django 4.1.3 on 2022-12-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(default='xxx@esp.sn', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
