# Generated by Django 4.1.3 on 2022-12-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0004_alter_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
