# Generated by Django 4.1.3 on 2022-12-08 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0006_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('category_hobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='forum_polytechnicien.categoryhobbie')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(to='forum_polytechnicien.hobbie'),
        ),
    ]
