# Generated by Django 4.1.3 on 2022-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0009_alter_categoryhobbie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhobbie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobbie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
