# Generated by Django 4.1.3 on 2022-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0014_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='forum_polytechnicien.hobbie', verbose_name="Centre d'intêret"),
        ),
    ]
