# Generated by Django 4.1.3 on 2022-12-14 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0015_alter_user_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryhobbie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryhobbie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AddField(
            model_name='hobbie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobbie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
    ]
