# Generated by Django 4.1.3 on 2022-12-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0018_categoryhobbie_created_at_categoryhobbie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
