# Generated by Django 4.1.3 on 2022-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0020_answer_comment_publication_question_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requestmodification',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
