# Generated by Django 4.1.3 on 2023-01-08 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0022_alter_publication_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='questions', to='forum_polytechnicien.hobbie', verbose_name="Centre d'intêret"),
        ),
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
