# Generated by Django 4.1.3 on 2023-01-15 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0023_alter_question_hobbies_alter_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
