# Generated by Django 4.1.3 on 2023-01-18 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0024_alter_publication_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='commentateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='publications', to='forum_polytechnicien.hobbie', verbose_name="Centre d'intêret"),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='users', to='forum_polytechnicien.hobbie', verbose_name="Centre d'intêret"),
        ),
    ]
