# Generated by Django 4.1.3 on 2023-01-18 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0025_alter_comment_commentator_alter_publication_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='répondeur'),
        ),
    ]
