# Generated by Django 4.1.3 on 2023-03-27 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_polytechnicien', '0030_discussion_message_user_discuss_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discuss_with',
            field=models.ManyToManyField(through='forum_polytechnicien.Discussion', to=settings.AUTH_USER_MODEL, verbose_name='discuter_avec'),
        ),
    ]
